#!/bin/sh
#
# PROVIDE: minecraft
# REQUIRE: LOGIN DAEMON NETWORKING mountcritlocal
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local to enable the minecraft server:
#
# minecraft_enable="YES"
# minecraft_user="<run server as this user>"
# minecraft_chdir="<run server in this directory>"
# minecraft_path="<path to minecraft_server.jar>"
# minecraft_flags="<set as needed>"
#
# For default setup, create a user named 'minecraft', set its home directory
# to /srv/minecraft, and place minecraft_server.jar into /srv/minecraft
#
# See minecraft_server.jar for flags

. /etc/rc.subr

name=blazenarchy_waterfall
rcvar=blazenarchy_enable

load_rc_config ${name}

command=/usr/local/bin/screen
pidfile=/var/run/blazenarchy_main.pid

start_cmd="minecraft_start"
stop_cmd="minecraft_start"
status_cmd="minecraft_start"

: ${blazenarchy_enable="NO"}=
: ${minecraft_user="minecraft"}
: ${minecraft_chdir="/srv/blazenarchy/waterfall"}
: ${minecraft_path="/srv/blazenarchy/waterfall/server.jar"}
: ${minecraft_flags=""}
: ${minecraft_args="/usr/local/bin/java -Xmx1G -Xms1G \
                    -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing \
                    -XX:ParallelGCThreads=4 -XX:+AggressiveOpts \
                    -DIReallyKnowWhatIAmDoingISwear \
                    -jar ${minecraft_path} ${minecraft_flags} nogui"}

minecraft_start() {
    unset "${rc_arg}_cmd"
    minecraft_flags="-d -m -S ${name} ${minecraft_args}"
    if minecraft_running; then
        echo "${name} already running?"
    else
        run_rc_command "start"
    fi
}

minecraft_stop() {
    local cmd
    cmd="${command} -p 0 -S ${name} -X eval 'stuff stop\015'"
    if minecraft_running; then
        echo "Stopping ${name}."
        su -m ${minecraft_user} -c "${cmd}"
    fi
}

minecraft_status() {
    if minecraft_running; then
        echo "${name} is running."
    else
        echo "${name} is not running."
    fi
}

minecraft_running() {
    local check ses
    ses="${name}"
    check=`su -m ${minecraft_user} -c "${command} -list" | grep ${ses}`
    if [ "$check" ]; then
        return 0
    else
        return 1
    fi
}

run_rc_command "$1"
