listeners:
- query_port: 25565
  motd: '&c&l&k!&6&l&k!&e&l&k!&f&lBlazenarchy&e&l&k!&6&l&k!&c&l&k!&a - Another MC
    Anarchy Server&r&f'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    blazenarchy.net: queue
  ping_passthrough: false
  priorities:
  - queue
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 80
  tab_size: 80
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - waterqueue.queue.normal
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - waterqueue.queue.admin
log_pings: true
connection_throttle_limit: 1
server_connect_timeout: 5000
timeout: 30000
stats: d699e488-2f00-40ea-a2e4-5102c5d5f09d
player_limit: 80
ip_forward: true
groups:
  wnuke:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  queue:
    motd: Blazenarchy Queue
    address: localhost:25566
    restricted: false
  main:
    motd: Blazenarchy
    address: localhost:25567
    restricted: false
